apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: poker-tool-backend
  name: poker-tool-backend
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: poker-tool-service-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: poker-tool-backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

